name: Build PackyCode macOS app

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
    paths:
      - '**'

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app
        run: |
          python setup.py py2app -q

      - name: Archive app (zip)
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent PackyCode.app PackyCode-macOS.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PackyCode-macOS
          path: |
            dist/PackyCode-macOS.zip

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/PackyCode-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

